spring:
  config:
    import: someapplication.yml

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: America/New_York
---

spring:
  config:
    activate:
      on-profile: dev

#  datasource:
#    url: jdbc:postgresql://localhost:5432/codesamples1
#    username: postgres
#    password: admin
  codesamples1ds:
    url: jdbc:postgresql://localhost:5432/codesamples1
    username: postgres
    password: admin
  codesamples2ds:
    url: jdbc:postgresql://localhost:5432/codesamples1
    username: postgres
    password: admin
  jpa:
    show-sql: true
